services:
  - type: web
    name: discord-music-bot
    env: node
    plan: free
    buildCommand: npm install
    startCommand: NODE_ENV=production node index.js
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
