// Guía para regenerar el token del bot Discord
console.log('🔧 GUÍA PARA REGENERAR TOKEN DEL BOT');
console.log('=====================================');
console.log('');
console.log('1. Ve a: https://discord.com/developers/applications');
console.log('2. Selecciona tu aplicación (LanaMusic)');
console.log('');
console.log('3. 📋 En la sección "General Information":');
console.log('   ✅ App URL: https://lanamusic.onrender.com/');
console.log('   ✅ Terms of Service URL: https://lanamusic.onrender.com/terms');
console.log('   ✅ Privacy Policy URL: https://lanamusic.onrender.com/privacy');
console.log('');
console.log('4. 🔑 En la sección "Bot":');
console.log('   ✅ Haz clic en "Reset Token"');
console.log('   ✅ Confirma la regeneración');
console.log('   ✅ COPIA EL NUEVO TOKEN COMPLETO');
console.log('');
console.log('5. 🔧 En la sección "OAuth2" → "General":');
console.log('   ✅ Redirect URIs:');
console.log('      - https://lanamusic.onrender.com/');
console.log('      - https://lanamusic.onrender.com/oauth2/callback');
console.log('');
console.log('6. 🔧 En la sección "General Information":');
console.log('   ✅ Interactions Endpoint URL: https://lanamusic.onrender.com/interactions');
console.log('   ✅ App URL: https://lanamusic.onrender.com/');
console.log('   ✅ Terms of Service URL: https://lanamusic.onrender.com/terms');
console.log('   ✅ Privacy Policy URL: https://lanamusic.onrender.com/privacy');
console.log('');
console.log('7. 🔧 En la sección "OAuth2" → "URL Generator":');
console.log('   ✅ Scopes: bot, applications.commands');
console.log('   ✅ Bot Permissions: Send Messages, Use Slash Commands, etc.');
console.log('');
console.log('8. 🚀 En Render Dashboard:');
console.log('   ✅ Ve a Environment Variables');
console.log('   ✅ Actualiza DISCORD_TOKEN con el nuevo token');
console.log('   ✅ Guarda los cambios');
console.log('');
console.log('9. 🎯 Privileged Gateway Intents (MUY IMPORTANTE):');
console.log('   ✅ PRESENCE INTENT: Activado');
console.log('   ✅ SERVER MEMBERS INTENT: Activado');
console.log('   ✅ MESSAGE CONTENT INTENT: Activado');
console.log('');
console.log('💡 CONSEJO: Después de regenerar el token, espera 2-3 minutos');
console.log('    antes de que Render redespliegue automáticamente.');
console.log('');
console.log('🔗 URL de tu bot desplegado: https://lanamusic.onrender.com/');
console.log('🔗 Health check: https://lanamusic.onrender.com/health');
console.log('🔗 Diagnóstico: https://lanamusic.onrender.com/diagnose');
